# Generated by Django 5.1.6 on 2026-01-17 08:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_province_alter_district_name_district_province_and_more'),
        ('families', '0003_alter_family_options_and_more'),
        ('students', '0002_student_cell_student_district_old_student_sector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='student',
            name='district',
        ),
        migrations.RemoveField(
            model_name='student',
            name='district_old',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sponsorship_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='village',
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01', help_text='YYYY-MM-DD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('transferred', 'Transferred'), ('graduated', 'Graduated'), ('dropped_out', 'Dropped Out')], default='enrolled', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='families.family'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentphoto',
            name='captured_via_camera',
            field=models.BooleanField(default=False, help_text='Was this photo captured using device camera?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.school'),
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=20)),
                ('academic_year', models.CharField(default='2024', max_length=20)),
                ('marks', models.DecimalField(decimal_places=2, help_text='Marks out of 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('teacher_remark', models.TextField(blank=True, help_text="Teacher's comments or remarks")),
                ('report_card_image', models.ImageField(blank=True, null=True, upload_to='students/reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year', 'term', 'subject'],
                'unique_together': {('student', 'subject', 'term', 'academic_year')},
            },
        ),
        migrations.DeleteModel(
            name='AcademicRecord',
        ),
    ]
