# Generated by Django 5.1.6 on 2026-01-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_age_remove_student_cell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='disability_description',
            field=models.TextField(blank=True, help_text='Detailed description of the disability and any special needs', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='disability_types',
            field=models.CharField(blank=True, help_text='Comma-separated list of disabilities (e.g., visual, hearing, mobility)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='has_disability',
            field=models.BooleanField(default=False, help_text='Does the student have any disability?'),
        ),
    ]
