# Generated by Django 5.2.10 on 2026-01-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_disability_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sponsorship_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('graduated', 'Graduated')], default='pending', max_length=20),
        ),
    ]
