# Generated by Django 5.1.6 on 2026-02-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentmark_academic_year_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmark',
            options={'ordering': ['-academic_year__name', 'term', 'subject']},
        ),
    ]
