# Generated by Django 5.1.6 on 2026-02-07 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_academic_year'),
        ('students', '0011_alter_studentmark_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmaterial',
            options={'ordering': ['-academic_year__name', 'student__first_name']},
        ),
        migrations.AlterField(
            model_name='studentmaterial',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_materials', to='core.academicyear'),
        ),
    ]
