# Generated by Django 5.1.6 on 2026-02-09 08:42

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_studentmaterial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentphoto',
            name='image',
            field=models.ImageField(upload_to=students.models.student_photo_path),
        ),
    ]
