# Generated by Django 5.1.6 on 2026-02-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_partner'),
        ('students', '0013_alter_studentphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner organization if student comes from one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.partner'),
        ),
    ]
