# Generated by Django 5.1.6 on 2026-02-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_student_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_level',
            field=models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('tvet', 'TVET'), ('university', 'University')], default='primary', max_length=20),
        ),
    ]
