# Generated by Django 5.2.11 on 2026-03-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_partner_cell_partner_district_partner_province_and_more"),
        ("students", "0015_alter_student_school_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentEnrollmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_level", models.CharField(blank=True, max_length=50)),
                ("school_name", models.CharField(blank=True, max_length=200)),
                (
                    "school_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nursery", "Nursery"),
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("tvet", "TVET"),
                            ("university", "University"),
                        ],
                        max_length=20,
                    ),
                ),
                ("promoted_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="core.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_history_records",
                        to="core.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_history",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Enrollment",
                "verbose_name_plural": "Student Enrollments",
                "ordering": ["student__last_name", "academic_year__name"],
                "unique_together": {("student", "academic_year")},
            },
        ),
        migrations.AddField(
            model_name="studentmark",
            name="enrollment_history",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_marks",
                to="students.studentenrollmenthistory",
            ),
        ),
    ]
