# Generated by Django 5.2.10 on 2026-01-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coverage_status', models.CharField(choices=[('covered', 'Covered'), ('not covered', 'Not Covered')], default='not covered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('manage_insurance', 'Can manage insurance')],
            },
        ),
    ]
