# Generated by Django 5.2.10 on 2026-01-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_remove_family_student_family_cell_family_district_and_more'),
        ('insurance', '0001_initial'),
        ('students', '0002_student_cell_student_district_old_student_sector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthinsurance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Legacy Health Insurance', 'verbose_name_plural': 'Legacy Health Insurance Records'},
        ),
        migrations.AlterField(
            model_name='healthinsurance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_insurance', to='students.student'),
        ),
        migrations.CreateModel(
            name='FamilyInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_year', models.CharField(default='2024', help_text='Year of insurance coverage', max_length=4)),
                ('required_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coverage_status', models.CharField(choices=[('covered', 'Covered'), ('partially_covered', 'Partially Covered'), ('not_covered', 'Not Covered')], default='not_covered', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional comments or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_records', to='families.family')),
            ],
            options={
                'ordering': ['-insurance_year', '-created_at'],
                'permissions': [('manage_insurance', 'Can manage insurance')],
                'unique_together': {('family', 'insurance_year')},
            },
        ),
    ]
