# Generated by Django 5.1.6 on 2026-01-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_healthinsurance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyinsurance',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='familyinsurance',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='familyinsurance',
            name='payment_dates',
            field=models.TextField(blank=True, help_text='Dates of payments (comma-separated)'),
        ),
        migrations.AddField(
            model_name='familyinsurance',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks or notes'),
        ),
    ]
