# Generated by Django 5.1.6 on 2026-02-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_familyinsurance_academic_year_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyinsurance',
            options={'ordering': ['-insurance_year__name', '-created_at'], 'permissions': [('manage_insurance', 'Can manage insurance')]},
        ),
    ]
