# Generated by Django 5.1.6 on 2026-01-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_province_alter_district_name_district_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Account holder name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Name of the bank', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standard fee amount per student', max_digits=10),
        ),
        migrations.AddField(
            model_name='school',
            name='headteacher_email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='headteacher_mobile',
            field=models.CharField(blank=True, help_text='Mobile phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='headteacher_name',
            field=models.CharField(blank=True, help_text='Full name of school headteacher', max_length=200, null=True),
        ),
    ]
