# Generated by Django 5.1.6 on 2026-02-11 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='core.cell'),
        ),
        migrations.AddField(
            model_name='partner',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='core.district'),
        ),
        migrations.AddField(
            model_name='partner',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='core.province'),
        ),
        migrations.AddField(
            model_name='partner',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='core.sector'),
        ),
        migrations.AddField(
            model_name='partner',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='core.village'),
        ),
    ]
