# Generated by Django 5.1.15 on 2026-04-10 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_partner_cell_partner_district_partner_province_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication"),
                            ("action", "Action"),
                            ("export", "Export"),
                            ("security", "Security"),
                        ],
                        default="action",
                        max_length=20,
                    ),
                ),
                ("action", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("path", models.CharField(blank=True, default="", max_length=255)),
                ("method", models.CharField(blank=True, default="", max_length=10)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System activity log",
                "verbose_name_plural": "System activity logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="core_system_created_e735f4_idx"
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="core_system_event_t_600c35_idx",
                    ),
                    models.Index(
                        fields=["username", "created_at"],
                        name="core_system_usernam_a5d38d_idx",
                    ),
                ],
            },
        ),
    ]
