# Generated by Django 5.1.6 on 2026-01-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('students', '0003_remove_student_age_remove_student_cell_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2024', max_length=20)),
                ('school_name', models.CharField(blank=True, help_text='School name for this fee record', max_length=200)),
                ('class_level', models.CharField(blank=True, max_length=50)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('payment_dates', models.TextField(blank=True, help_text='Dates of payments (comma-separated)')),
                ('comments', models.TextField(blank=True, help_text='Additional comments or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'School Fees',
                'ordering': ['-academic_year', '-created_at'],
                'permissions': [('manage_fees', 'Can manage fees')],
            },
        ),
        migrations.DeleteModel(
            name='SchoolFees',
        ),
    ]
