# Generated by Django 5.1.6 on 2026-01-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_schoolfee_delete_schoolfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfee',
            name='term',
            field=models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='1', max_length=1),
        ),
    ]
