# Generated by Django 5.2.10 on 2026-01-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_schoolfee_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfee',
            name='term',
            field=models.CharField(choices=[('1', 'TERM 1'), ('2', 'TERM 2'), ('3', 'TERM 3')], default='1', max_length=1),
        ),
    ]
