# Generated by Django 5.1.6 on 2026-02-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_schoolfee_academic_year_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolfee',
            options={'ordering': ['-academic_year__name', '-created_at'], 'permissions': [('manage_fees', 'Can manage fees')], 'verbose_name_plural': 'School Fees'},
        ),
    ]
