# Generated by Django 5.2.11 on 2026-03-02 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0009_alter_schoolfee_payment_date"),
        ("students", "0016_studentenrollmenthistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolfee",
            name="enrollment_history",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="school_fees",
                to="students.studentenrollmenthistory",
            ),
        ),
    ]
