# Generated by Django 5.2.10 on 2026-01-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_district_alter_school_district_sector_cell_and_more'),
        ('families', '0001_initial'),
        ('students', '0002_student_cell_student_district_old_student_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='student',
        ),
        migrations.AddField(
            model_name='family',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='core.cell'),
        ),
        migrations.AddField(
            model_name='family',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='core.district'),
        ),
        migrations.AddField(
            model_name='family',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='core.sector'),
        ),
        migrations.AddField(
            model_name='family',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='core.village'),
        ),
        migrations.CreateModel(
            name='FamilyStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(default='Child', help_text='e.g., Child, Sibling, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_students', to='families.family')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('family', 'student')},
            },
        ),
    ]
