# Generated by Django 5.1.6 on 2026-01-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_province_alter_district_name_district_province_and_more'),
        ('families', '0002_remove_family_student_family_cell_family_district_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['head_of_family'], 'verbose_name_plural': 'Families'},
        ),
        migrations.RenameField(
            model_name='family',
            old_name='guardian_phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='family',
            name='family_size',
        ),
        migrations.RemoveField(
            model_name='family',
            name='guardian_email',
        ),
        migrations.RemoveField(
            model_name='family',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='vulnerability_notes',
        ),
        migrations.AddField(
            model_name='family',
            name='address_description',
            field=models.TextField(blank=True, help_text='Detailed address or landmarks', null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='family_code',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='family',
            name='head_of_family',
            field=models.CharField(default='', help_text='Full Name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional comments or notes'),
        ),
        migrations.AddField(
            model_name='family',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='core.province'),
        ),
    ]
