# Generated by Django 5.1.6 on 2026-01-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_alter_family_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='national_id',
            field=models.CharField(default='', help_text='National ID (e.g., ID Card Number)', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
