# Generated by Django 5.1.6 on 2026-01-17 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_family_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='total_family_members',
            field=models.IntegerField(default=1, help_text='Total number of family members', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
