# Generated by Django 5.2.10 on 2026-04-08 08:00

from django.db import migrations, models


def backfill_mutuelle_statuses(apps, schema_editor):
    Family = apps.get_model("families", "Family")
    FamilyInsurance = apps.get_model("insurance", "FamilyInsurance")

    supported_family_ids = set(
        FamilyInsurance.objects.filter(amount_paid__gt=0).values_list("family_id", flat=True)
    )

    Family.objects.filter(id__in=supported_family_ids).update(
        payment_ability="unable_to_pay",
        mutuelle_support_status="supported",
    )
    Family.objects.exclude(id__in=supported_family_ids).update(
        payment_ability="able_to_pay",
        mutuelle_support_status="not_supported",
    )


def reverse_backfill_mutuelle_statuses(apps, schema_editor):
    Family = apps.get_model("families", "Family")
    Family.objects.update(
        payment_ability="able_to_pay",
        mutuelle_support_status="not_supported",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("families", "0006_family_parents_guardian"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="mutuelle_support_status",
            field=models.CharField(
                choices=[
                    ("supported", "Supported"),
                    ("not_supported", "Not Supported"),
                ],
                db_index=True,
                default="not_supported",
                help_text="Whether the organization supports this family's Mutuelle de Sante.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="payment_ability",
            field=models.CharField(
                choices=[
                    ("able_to_pay", "Able to Pay"),
                    ("unable_to_pay", "Unable to Pay"),
                ],
                db_index=True,
                default="able_to_pay",
                help_text="Whether the family can pay Mutuelle de Sante by themselves.",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            backfill_mutuelle_statuses,
            reverse_backfill_mutuelle_statuses,
        ),
    ]
