# Generated by Django 5.1.15 on 2026-04-08 13:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("families", "0007_family_mutuelle_support_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MutuelleContributionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_per_person",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3000.00"),
                        help_text="Mutuelle contribution amount charged per family member.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mutuelle Contribution Setting",
                "verbose_name_plural": "Mutuelle Contribution Settings",
            },
        ),
    ]
